# The introduction of Numpy
### Arrays

In [1]:
import numpy as np
v = np.array ([1 ,2 ,3 ,4])
M = np.array ([[1 , 2], [3, 4]])

In [2]:
print(type(v)) 
print(type(M))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
print(v.shape)
print(M.shape)
print(M.size)
print(M.dtype)

(4,)
(2, 2)
4
int32


In [7]:
M = np.array ([[1 , 2], [3, 4]] , dtype=complex ) 
print(M)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


### Using array-generating functions

In [8]:
np.arange (0, 10, 1) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace (0,10,11) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### mgrid

In [10]:
x,y = np.mgrid[0:3,0:2]
print(x)
print(y)

[[0 0]
 [1 1]
 [2 2]]
[[0 1]
 [0 1]
 [0 1]]


### Diagonal and zero matrix

In [20]:
np.diag([1 ,2 ,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
np.zeros((3 ,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
mat = np.array([[1,2,1],[3,2,5],[4,2,6]])
print('mat:',mat)
print('diag element:',np.diag(mat))

mat: [[1 2 1]
 [3 2 5]
 [4 2 6]]
diag element: [1 2 6]


### Array access

In [28]:
M = np.random.rand(3,3) 
print('M:',M)
print('M[1,1]:',M[1,1])

M: [[0.06365406 0.21163432 0.78829338]
 [0.03296685 0.46054028 0.67933028]
 [0.79039915 0.23231549 0.02407038]]
M[1,1]: 0.4605402775950055


In [30]:
# Access the first row
print(M[0,:])

[0.06365406 0.21163432 0.78829338]


In [31]:
# Access the first column
print(M[:,0])

[0.06365406 0.03296685 0.79039915]


In [32]:
M[1,:] = 0
print(M)

[[0.06365406 0.21163432 0.78829338]
 [0.         0.         0.        ]
 [0.79039915 0.23231549 0.02407038]]


### Array slicing

In [33]:
print(M[1:3]) # output the second and third row, which are indexed by row=1 and row=2

[[0.         0.         0.        ]
 [0.79039915 0.23231549 0.02407038]]


In [34]:
print(M[1:3 ,1:2])

[[0.        ]
 [0.23231549]]


### Negative indexing

In [36]:
print(M[-2])

[0. 0. 0.]


In [37]:
print(M[-1])

[0.79039915 0.23231549 0.02407038]


### strided access

In [38]:
print(M[::2 ,::2])  # which equals to M[:3:2 ,:3:2]

[[0.06365406 0.78829338]
 [0.79039915 0.02407038]]


In [53]:
print(M[:-1:2 ,:-1:2])  # -1 is not including in the slice

[[0.06365406]]


In [50]:
a = np.arange(9)
print(a)
print(a[:-1:2])
print(a[::2])

[0 1 2 3 4 5 6 7 8]
[0 2 4 6]
[0 2 4 6 8]


### Reverse the array

In [52]:
a = np.arange(9)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0]


### Array operations - scalar

In [57]:
print(M)

[[0.06365406 0.21163432 0.78829338]
 [0.         0.         0.        ]
 [0.79039915 0.23231549 0.02407038]]


In [58]:
print(M*2)

[[0.12730812 0.42326864 1.57658676]
 [0.         0.         0.        ]
 [1.58079831 0.46463099 0.04814076]]


In [59]:
print(M+2)

[[2.06365406 2.21163432 2.78829338]
 [2.         2.         2.        ]
 [2.79039915 2.23231549 2.02407038]]


### Array operations — matrix multiplication

In [60]:
print(M*M)

[[4.05183918e-03 4.47890856e-02 6.21406456e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.24730822e-01 5.39704887e-02 5.79383211e-04]]


In [61]:
print(np.dot(M,M))

[[0.62711826 0.19660415 0.06915259]
 [0.         0.         0.        ]
 [0.06933732 0.17286751 0.62364581]]


In [62]:
print(np.matmul(M,M))

[[0.62711826 0.19660415 0.06915259]
 [0.         0.         0.        ]
 [0.06933732 0.17286751 0.62364581]]


### Vectorize

In [63]:
def Theta(x):
    if x>=0:
        return 1
    else:
        return 0

In [66]:
v =  np.arange(1,5)
Theta(v)   # Theta cannot accept the vector data type

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [65]:
Tvec = np.vectorize(Theta)
print(Tvec(v))

[1 1 1 1]


In [67]:
print(Tvec(1.0))

1


### Arrays in conditions

In [68]:
v

array([1, 2, 3, 4])

In [69]:
(v>3).any()

True

In [70]:
(v>3).all()

False